package com.vr.domain;
// Generated 2017-8-13 11:29:14 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Posts generated by hbm2java
 */
@Entity
@Table(name = "posts", catalog = "vr")
public class Posts implements java.io.Serializable {

	private Integer id;
	private String title;
	private String contents;
	private String date;
	private Integer posterId;
	private String posterName;
	private Integer totalComments;
	private String theme;
    private boolean good;
    private Integer upvote;
    private Integer downvote;
    private String tag;
	public Posts() {
	}

	public Posts(String title, String contents, String date, Integer posterId, String posterName, Integer totalComments , String theme, boolean good, Integer upvote, Integer downvote, String tag) {
		this.title = title;
		this.contents = contents;
		this.date = date;
		this.posterId = posterId;
		this.posterName = posterName;
		this.totalComments = totalComments;
		this.theme = theme;
		this.good = good;
		this.upvote = upvote;
		this.downvote = downvote;
		this.tag = tag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "contents")
	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

	@Column(name = "date")
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "poster_id")
	public Integer getPosterId() {
		return this.posterId;
	}

	public void setPosterId(Integer posterId) {
		this.posterId = posterId;
	}
	
	@Column(name = "poster_name")
	public String getPosterName() {
		return this.posterName;
	}

	public void setPosterName(String posterName) {
		this.posterName = posterName;
	}
	
	@Column(name = "total_comments")
	public Integer getTotalComments() {
		return this.totalComments;
	}

	public void setTotalComments(Integer totalComments) {
		this.totalComments = totalComments;
	}

	@Column(name = "theme")
	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	@Column(name = "good")
	public boolean getGood() {
		return this.good;
	}

	public void setGood(boolean good) {
		this.good = good;
	}
	
	@Column(name = "updown")
	public Integer getUpvote() {
		return this.upvote;
	}

	public void setUpvote(Integer upvote) {
		this.upvote = upvote;
	}
	
	@Column(name = "downvote")
	public Integer getDownvote() {
		return this.downvote;
	}

	public void setDownvote(Integer downvote) {
		this.downvote=downvote;
	}
	
	@Column(name = "tag")
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag=tag;
	}
}
